name: inspirio
description: Inspirio.

version: 1.5.0+9

environment:
  sdk: '>=3.0.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter


  cupertino_icons: ^1.0.2
  firebase_core: ^2.13.1
  google_mobile_ads: ^3.0.0
  get: ^4.6.5
  path_provider: ^2.0.15
  firebase_storage: ^11.2.2
  share: ^2.0.4
  cached_network_image: ^3.2.3
  google_fonts: ^4.0.4
  flutter_material_color_picker: ^1.2.0
  card_swiper: ^2.0.4
  google_nav_bar: ^5.0.6
  flutter_floating_bottom_bar: ^1.1.0
  firebase_auth: ^4.7.2
  google_sign_in: ^6.1.4
  flutter_colorpicker: ^1.0.3
  loading_animation_widget: ^1.2.0+4
  provider: ^6.0.5
  url_launcher: ^6.1.12
  flutter_staggered_animations: ^1.1.1
  image_gallery_saver: ^2.0.3
  iconsax: ^0.0.8
  shared_preferences: ^2.2.1
  bootstrap_icons: ^1.11.1
  image_picker: ^1.0.4
  firebase_app_check: ^0.2.1+2
  chips_choice: ^3.0.1
  rename: ^3.0.1
  palette_generator: ^0.3.3+3

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:

  uses-material-design: true
  assets:
    - assets/image/
    - lib/images/

  fonts:
    - family: Anurati
  
      fonts:
        - asset: assets/fonts/Anurati.otf
